#!/bin/bash
### BEGIN INIT INFO
# Provides:          SoftChef
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: dovepass -jitr
# Description:       dovepass daemon
### END INIT INFO

dovepass -jitr
